runtime config/plugin/syntastic.vim
runtime config/plugin/vim-airline.vim
runtime config/plugin/tagbar.vim
runtime config/plugin/vim-yardoc.vim
runtime config/plugin/php.vim.vim
runtime config/plugin/vim-highlight.vim
runtime config/plugin/jscomplete-vim.vim
runtime config/plugin/vim-javascript-syntax.vim
runtime config/plugin/javascript-libraries-syntax.vim
runtime config/plugin/vim-multiple-cursor.vim
runtime config/plugin/vim-easy-align.vim
