# Utilise Xterm, mais en 256 couleurs (pour le thème VIM)
export TERM='xterm-256color'

# Set up the prompt
autoload -Uz promptinit
promptinit
#prompt adam1

setopt histignorealldups sharehistory

# Use emacs keybindings even if our EDITOR is set to vi
bindkey -e
bindkey '[1~' beginning-of-line			# [Origin]
bindkey '[4~' end-of-line					# [Fin]
bindkey '^[[2~' overwrite-mode				# [Insert]
bindkey '^[[3~' delete-char					# [Suppr]
bindkey '[5~' history-search-backward		# [Page-Up]
bindkey '[6~' history-search-forward		# [Page-Down]

# Keep 1000 lines of history within the shell and save it to ~/.zsh_history:
HISTSIZE=1000
SAVEHIST=1000
HISTFILE=~/.zsh_history

# Use modern completion system
autoload -Uz compinit
compinit

zstyle ':completion:*' auto-description 'specify: %d'
zstyle ':completion:*' completer _expand _complete _correct _approximate
zstyle ':completion:*' format 'Completing %d'
zstyle ':completion:*' group-name ''
zstyle ':completion:*' menu select=2
eval "$(dircolors -b)"
zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}
zstyle ':completion:*' list-colors ''
zstyle ':completion:*' list-prompt %SAt %p: Hit TAB for more, or the character to insert%s
zstyle ':completion:*' matcher-list '' 'm:{a-z}={A-Z}' 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=* l:|=*'
zstyle ':completion:*' menu select=long
zstyle ':completion:*' select-prompt %SScrolling active: current selection at %p%s
zstyle ':completion:*' use-compctl false
zstyle ':completion:*' verbose true

zstyle ':completion:*:*:kill:*:processes' list-colors '=(#b) #([0-9]#)*=0=01;31'
zstyle ':completion:*:kill:*' command 'ps -u $USER -o pid,%cpu,tty,cputime,cmd'

# Include other files
source ~/.zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh 		# Coloration syntaxique à la volée

source ~/.zsh/ssh_agent				# Pour que ssh-add marche sans se plaindre de ssh-agent

#	Fichiers de config perso à la machine
for conf_file in ~/.zsh/config/* ;
do
	source $conf_file ;
done

# USER part
# 	Interface de demande
autoload -U colors && colors
PROMPT="%{${fg_bold[red]}%}%n%{${fg[blue]}%}@%{${fg[green]}%}%m %{${fg[magenta]}%}%~ %{${fg_bold[yellow]}%}%#%{${reset_color}%} "

#	Variables
export MOZILLA_FIVE_HOME=/usr/lib/mozilla

#	Options
alias -s pdf='okular'
setopt autocd correctall

#	Alias
alias ls='ls --color=auto --group-directories-first -Fh'
alias ll='ls -l'
alias la='ll -a'

alias vim='vim -p'			# Ouvre les paramètres comme des onglets au lieu de buffers
alias 7z_max="7z a -t7z -m0=lzma -mx=9 -mfb=64 -md=32m -ms=on"

alias maj="apti update && apti full-upgrade"
maj_calibre() {
	sudo -v && wget -nv -O- https://download.calibre-ebook.com/linux-installer.py | sudo python -c "import sys; main=lambda x:sys.stderr.write('Download failed\n'); exec(sys.stdin.read()); main('/opt')"
}

find_php() {
	# $1 : expression recherchée
	# $2 : chemin
	# $3 : option supplémentaires
	arg_path=$2
	if [ -z $arg_path ]; then
		arg_path="."
	fi
	arg_options=$3
	if [ -z $arg_options ]; then
		arg_options="-n"
	fi
	find $arg_path -type f -iname "*.php" -print0 | xargs --null grep $arg_options $1
}
